// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB37twTxgOuuKnBxfKuxPQxkjuClESpUYw',
    appId: '1:677222401326:web:14fe97c52fff88538426bf',
    messagingSenderId: '677222401326',
    projectId: 'enpit2024-flutter-test',
    authDomain: 'enpit2024-flutter-test.firebaseapp.com',
    storageBucket: 'enpit2024-flutter-test.appspot.com',
    measurementId: 'G-9G17DT5EP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHTiCgCcB9arg5AaE_wlRE64im7swIc24',
    appId: '1:677222401326:android:60c819e6c38e7a378426bf',
    messagingSenderId: '677222401326',
    projectId: 'enpit2024-flutter-test',
    storageBucket: 'enpit2024-flutter-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9n733QWFWxr0hXBB69zVnBDwuFpPve1U',
    appId: '1:677222401326:ios:8b44ed79742f507f8426bf',
    messagingSenderId: '677222401326',
    projectId: 'enpit2024-flutter-test',
    storageBucket: 'enpit2024-flutter-test.appspot.com',
    iosBundleId: 'com.example.myWebApp20240926',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9n733QWFWxr0hXBB69zVnBDwuFpPve1U',
    appId: '1:677222401326:ios:1a68da72330b08358426bf',
    messagingSenderId: '677222401326',
    projectId: 'enpit2024-flutter-test',
    storageBucket: 'enpit2024-flutter-test.appspot.com',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB37twTxgOuuKnBxfKuxPQxkjuClESpUYw',
    appId: '1:677222401326:web:6016efe255e8cd738426bf',
    messagingSenderId: '677222401326',
    projectId: 'enpit2024-flutter-test',
    authDomain: 'enpit2024-flutter-test.firebaseapp.com',
    storageBucket: 'enpit2024-flutter-test.appspot.com',
    measurementId: 'G-4HLX5Y2MG7',
  );
}
